services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: laravel-app
          property: url
      - key: APP_KEY
        generateValue: true # Render will generate this for you on first deploy
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      # Firebase Environment Variables
      - key: FIREBASE_PROJECT_ID
        value: your-firebase-project-id # <-- GANTI DENGAN PROJECT ID ANDA
      - key: FIREBASE_CREDENTIALS
        value: your-firebase-credentials-json # <-- GANTI DENGAN ISI FILE JSON KREDENSIAL ANDA
